# Generated by Django 5.2.9 on 2026-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_userplant_is_for_swap_userplant_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Plant Image'),
        ),
    ]
