"""
Django settings for app_core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-w!4@1lfvovb*7o(e&co3%kntb^*5u=yng+!u20f2jown+zkmq*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost,http://127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')
if RENDER_EXTERNAL_HOSTNAME:
    if RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    https_host = f'https://{RENDER_EXTERNAL_HOSTNAME}'
    if https_host not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(https_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'mongoengine',
    'channels',
    'tailwind',
    'theme',
    'users',
    'feed',
    'market',
    'chat',
    'garden',
    'checks',
    'widget_tweaks',
]

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.notifications_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'app_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL in production, SQLite in development
DATABASE_URL = config('DATABASE_URL', default='')

if DATABASE_URL:
    try:
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
        }
    except Exception as e:
        if DEBUG:
            print(f"[WARNING] Invalid DATABASE_URL: {e}. Falling back to SQLite.")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('ta', _('Tamil')),
    ('te', _('Telugu')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False  # Prevent build crash on missing assets

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = '/'

# Google Gemini AI API Key (used only for Crop Recommendation)
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')

# Hugging Face API Key (used for Agrobot Chat)
HUGGINGFACE_API_KEY = config('HUGGINGFACE_API_KEY', default='')

# Plant.id API Key (used for plant health, disease, and encyclopedia checks)
PLANT_ID_API_KEY = config('PLANT_ID_API_KEY', default='')

# Razorpay Configuration
RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='')


# ML Model Configuration
# Set USE_ML_MODEL=True to use local ML model, False to use Gemini AI
USE_ML_MODEL = config('USE_ML_MODEL', default=True, cast=bool)
ML_MODEL_PATH = BASE_DIR / 'checks' / 'ml_models' / 'trained_plant_disease_model.keras'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary configuration — reads from .env or environment variables
_CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')
_CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='')
_CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='')

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': _CLOUDINARY_CLOUD_NAME,
    'API_KEY': _CLOUDINARY_API_KEY,
    'API_SECRET': _CLOUDINARY_API_SECRET,
    'SECURE': True,
}

# Django 4.2+ STORAGES dictionary (replaces DEFAULT_FILE_STORAGE & STATICFILES_STORAGE)
if _CLOUDINARY_CLOUD_NAME and _CLOUDINARY_API_KEY and _CLOUDINARY_API_SECRET:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.StaticFilesStorage',
        },
    }
    if DEBUG:
        print(f"[CLOUDINARY] Active — Cloud: {_CLOUDINARY_CLOUD_NAME}")
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.StaticFilesStorage',
        },
    }
    if DEBUG:
        print("[CLOUDINARY] NOT configured — falling back to local file storage.")

# Channels configuration
ASGI_APPLICATION = 'app_core.asgi.application'

REDIS_URL = config('REDIS_URL', default='')

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }

# MongoDB Configuration
import mongoengine

USE_MONGODB = config('USE_MONGODB', default=False, cast=bool)
MONGODB_URI = config('MONGODB_URI', default='')
MONGODB_DB_NAME = config('MONGODB_DB_NAME', default='farmers_platform')

if USE_MONGODB:
    if MONGODB_URI:
        # Connect to MongoDB Atlas lazily and avoid startup failures when Atlas is unavailable.
        try:
            mongoengine.connect(
                db=MONGODB_DB_NAME,
                host=MONGODB_URI,
                alias='default',
                connect=False,
                serverSelectionTimeoutMS=5000,
                connectTimeoutMS=5000
            )
            if DEBUG:
                print(f"[OK] MongoDB connection initialized for {MONGODB_DB_NAME}")
        except Exception as e:
            if DEBUG:
                print(f"[WARNING] MongoDB connection failed: {e}. Using SQLite only.")
    else:
        if DEBUG:
            print("[WARNING] USE_MONGODB=True but MONGODB_URI is missing. Using SQLite only.")
else:
    if DEBUG:
        print("[INFO] MongoDB support is disabled. Using SQLite for local development.")

NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"
