# Generated by Django 5.2.9 on 2026-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_orderfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
