# Generated by Django 5.2.9 on 2026-08-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Herbs', 'Herbs')], default='Vegetables', max_length=50),
        ),
    ]
